CREATE TABLE "sppd" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sppd_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"employeeId" integer,
	"purpose" text NOT NULL,
	"transport" varchar NOT NULL,
	"depart" varchar NOT NULL,
	"destination" varchar NOT NULL,
	"day" varchar NOT NULL,
	"departureDate" date NOT NULL,
	"returnDate" date NOT NULL,
	"createdAt" timestamp DEFAULT now(),
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "sppd" ADD CONSTRAINT "sppd_employeeId_user_id_fk" FOREIGN KEY ("employeeId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;