CREATE TABLE "sppdFollower" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sppdFollower_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sppdId" integer,
	"employeeId" text,
	"createdAt" timestamp DEFAULT now(),
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "sppdFollower" ADD CONSTRAINT "sppdFollower_sppdId_sppd_id_fk" FOREIGN KEY ("sppdId") REFERENCES "public"."sppd"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sppdFollower" ADD CONSTRAINT "sppdFollower_employeeId_user_id_fk" FOREIGN KEY ("employeeId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;